// Newsletter generation functions

/**
 * Generate HTML newsletter from clustered posts
 */
function generateNewsletter(clusters) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  const generatedAt = new Date().toLocaleString('en-US');
  
  let html = `
    <div class="newsletter-content">
      <h2 style="color: #1da1f2; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">
        X-Daily: ${today}
      </h2>
      <p style="color: #657786; margin-bottom: 20px;">
        Here are the top stories from your network today.
      </p>
  `;
  
  // Sort clusters by size (largest first)
  const sortedClusters = Object.entries(clusters)
    .sort((a, b) => b[1].length - a[1].length);
  
  sortedClusters.forEach(([clusterId, posts], index) => {
    const summary = generateClusterSummary(posts, index + 1);
    
    html += `
      <div class="topic">
        <div class="topic-header">${summary}</div>
    `;
    
    posts.forEach(post => {
      html += `
        <div class="post">
          <div class="handle">
            ${post.handle}
            <span class="date">${formatDate(post.timestamp)}</span>
          </div>
          <div class="content">${escapeHtml(post.clean_text || post.original_text).replace(/\n/g, '<br>')}</div>
      `;
      
      if (post.images && post.images.length > 0) {
        html += '<div class="media">';
        post.images.forEach(img => {
          html += `<img src="${escapeHtml(img)}" alt="Post image" />`;
        });
        html += '</div>';
      }
      
      html += '</div>';
    });
    
    html += '</div>';
  });
  
  html += `
      <p style="text-align: center; color: #888; font-size: 12px; margin-top: 40px;">
        Generated by X-Daily on ${generatedAt}
      </p>
    </div>
  `;
  
  return html;
}

/**
 * Generate a summary for a cluster of posts
 */
function generateClusterSummary(posts, clusterNumber) {
  if (posts.length === 0) return `Topic Group ${clusterNumber}`;
  
  // Simple summary: use first few words from the first post
  const firstPost = posts[0];
  const text = (firstPost.clean_text || firstPost.original_text || '').substring(0, 50);
  
  // Try to extract common keywords
  const allWords = posts
    .flatMap(p => (p.clean_text || p.original_text || '').toLowerCase().split(/\s+/))
    .map(w => w.replace(/[^\w]/g, ''))
    .filter(w => w.length > 3);
  
  const wordCounts = {};
  allWords.forEach(word => {
    wordCounts[word] = (wordCounts[word] || 0) + 1;
  });
  
  const topWords = Object.entries(wordCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([word]) => word);
  
  if (topWords.length > 0) {
    return `Topic ${clusterNumber}: ${topWords.join(', ')}`;
  }
  
  return `Topic Group ${clusterNumber}: ${text}...`;
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
