from pathlib import Path

from scripts.generate_sample_newsletter import generate_sample_newsletter
from src.generator.newsletter import NewsletterGenerator


def test_newsletter_uses_fixture_summaries_and_deterministic_dates():
    html = NewsletterGenerator().generate(
        [
            {
                "summary": "AI product updates",
                "posts": [
                    {
                        "handle": "OpenAI",
                        "timestamp": "2026-06-30T17:45:00Z",
                        "clean_text": "Developer note",
                        "images": [],
                    }
                ],
            }
        ],
        date="June 30, 2026",
        generated_at="2026-07-01 09:00:00",
    )

    assert "X-Daily: June 30, 2026" in html
    assert "AI product updates" in html
    assert "Generated by X-Daily Automation on 2026-07-01 09:00:00" in html
    assert "Topic Group 1" not in html


def test_newsletter_escapes_post_text_and_preserves_line_breaks():
    html = NewsletterGenerator().generate(
        {
            0: [
                {
                    "handle": "Example",
                    "timestamp": "2026-06-30T10:00:00Z",
                    "clean_text": "<script>alert('x')</script>\nsecond line",
                    "images": [],
                }
            ]
        },
        date="June 30, 2026",
        generated_at="2026-07-01 09:00:00",
    )

    assert "<script>alert" not in html
    assert "&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;<br>second line" in html


def test_generate_sample_newsletter_writes_html(tmp_path):
    output_path = tmp_path / "sample.html"

    generated_path = generate_sample_newsletter(output_path=output_path)
    html = Path(generated_path).read_text(encoding="utf-8")

    assert generated_path == output_path
    assert "Launch and space operations" in html
    assert "AI product updates" in html
