from jinja2 import Environment, select_autoescape
from datetime import datetime

class NewsletterGenerator:
    def __init__(self):
        self.environment = Environment(
            autoescape=select_autoescape(default_for_string=True)
        )
        self.template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                h1 { color: #1da1f2; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                .topic { margin-bottom: 30px; background: #f9f9f9; padding: 15px; border-radius: 8px; }
                .topic-header { font-size: 1.2em; font-weight: bold; margin-bottom: 10px; color: #444; }
                .post { border-left: 3px solid #1da1f2; padding-left: 10px; margin-bottom: 15px; }
                .handle { font-weight: bold; color: #657786; font-size: 0.9em; }
                .date { color: #aab8c2; font-size: 0.8em; }
                .content { margin-top: 5px; }
                img { max-width: 100%; border-radius: 5px; margin-top: 5px; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>X-Daily: {{ date }}</h1>
                <p>Here are the top stories from your network today.</p>
                
                {% for cluster in clusters %}
                <div class="topic">
                    <div class="topic-header">{{ cluster.summary }}</div>
                    {% for post in cluster.posts %}
                    <div class="post">
                        <div class="handle">@{{ post.handle }} <span class="date">{{ post.timestamp }}</span></div>
                        <div class="content">{{ post.clean_text | e | replace('\n', '<br>' | safe) }}</div>
                        {% if post.images %}
                        <div class="media">
                            {% for img in post.images %}
                            <img src="{{ img }}" />
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                
                <p style="text-align: center; color: #888; font-size: 0.8em; margin-top: 40px;">
                    Generated by X-Daily Automation on {{ generated_at }}
                </p>
            </div>
        </body>
        </html>
        """

    def generate(self, clustered_data, date: str | None = None, generated_at: str | None = None) -> str:
        """
        Render the HTML newsletter.
        clustered_data can be {cluster_id: [posts]} or
        [{"summary": "Topic", "posts": [...]}, ...].
        """
        template = self.environment.from_string(self.template_str)

        return template.render(
            date=date or datetime.now().strftime("%B %d, %Y"),
            clusters=self._clusters_list(clustered_data),
            generated_at=generated_at or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )

    def _clusters_list(self, clustered_data) -> list[dict]:
        if isinstance(clustered_data, list):
            clusters = []
            for index, cluster in enumerate(clustered_data, start=1):
                if isinstance(cluster, dict) and "posts" in cluster:
                    clusters.append({
                        "summary": cluster.get("summary") or f"Topic Group {index}",
                        "posts": cluster.get("posts") or []
                    })
                else:
                    clusters.append({
                        "summary": f"Topic Group {index}",
                        "posts": cluster
                    })
            return clusters

        clusters = []
        for index, (cluster_id, posts) in enumerate(clustered_data.items(), start=1):
            if isinstance(posts, dict) and "posts" in posts:
                summary = posts.get("summary") or f"Topic Group {self._topic_number(cluster_id, index)}"
                cluster_posts = posts.get("posts") or []
            else:
                summary = f"Topic Group {self._topic_number(cluster_id, index)}"
                cluster_posts = posts

            clusters.append({
                "summary": summary,
                "posts": cluster_posts
            })
        return clusters

    @staticmethod
    def _topic_number(cluster_id, fallback: int) -> int:
        try:
            return int(cluster_id) + 1
        except (TypeError, ValueError):
            return fallback
