from jinja2 import Template
from datetime import datetime

class NewsletterGenerator:
    def __init__(self):
        self.template_str = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                h1 { color: #1da1f2; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                .topic { margin-bottom: 30px; background: #f9f9f9; padding: 15px; border-radius: 8px; }
                .topic-header { font-size: 1.2em; font-weight: bold; margin-bottom: 10px; color: #444; }
                .post { border-left: 3px solid #1da1f2; padding-left: 10px; margin-bottom: 15px; }
                .handle { font-weight: bold; color: #657786; font-size: 0.9em; }
                .date { color: #aab8c2; font-size: 0.8em; }
                .content { margin-top: 5px; }
                img { max-width: 100%; border-radius: 5px; margin-top: 5px; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>X-Daily: {{ date }}</h1>
                <p>Here are the top stories from your network today.</p>
                
                {% for cluster in clusters %}
                <div class="topic">
                    <div class="topic-header">{{ cluster.summary }}</div>
                    {% for post in cluster.posts %}
                    <div class="post">
                        <div class="handle">@{{ post.handle }} <span class="date">{{ post.timestamp }}</span></div>
                        <div class="content">{{ post.clean_text | replace('\n', '<br>') | safe }}</div>
                        {% if post.images %}
                        <div class="media">
                            {% for img in post.images %}
                            <img src="{{ img }}" />
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
                
                <p style="text-align: center; color: #888; font-size: 0.8em; margin-top: 40px;">
                    Generated by X-Daily Automation on {{ generated_at }}
                </p>
            </div>
        </body>
        </html>
        """

    def generate(self, clustered_data: dict) -> str:
        """
        Render the HTML newsletter.
        clustered_data format expected: [{"summary": "Topic 1", "posts": [...]}, ...]
        """
        template = Template(self.template_str)
        today = datetime.now().strftime("%B %d, %Y")
        
        # Transform dict {id: [posts]} to list sorted by size/importance
        clusters_list = []
        for cid, posts in clustered_data.items():
            # Simple summary logic can be improved in Analyzer
            summary = f"Topic Group {cid+1}"
            clusters_list.append({"summary": summary, "posts": posts})
            
        return template.render(
            date=today,
            clusters=clusters_list,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
